import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Divyansh - portfolio",
  description: "Generated by create next app",
  icons:{
    icon:'./logo.png'
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="min-h-full flex flex-col" suppressHydrationWarning>{children}</body>
    </html>
  );
}